# Core
hard_tabs = true
newline_style = "Unix"

# Miscellaneous
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
#format_code_in_doc_comments = true # Incompatible with `hard_tabs = true` and `clippy::tabs_in_doc_comments`
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
reorder_impl_items = true
reorder_modules = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
wrap_comments = true

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
reorder_imports = true
