table! {
    /// Representation of the `saved_roll_aliases` table.
    ///
    /// (Automatically generated by Diesel.)
    saved_roll_aliases (id) {
        /// The `id` column of the `saved_roll_aliases` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Nullable<Integer>,
        /// The `saved_roll_id` column of the `saved_roll_aliases` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        saved_roll_id -> Integer,
        /// The `alias` column of the `saved_roll_aliases` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        alias -> Text,
    }
}

table! {
    /// Representation of the `saved_rolls` table.
    ///
    /// (Automatically generated by Diesel.)
    saved_rolls (id) {
        /// The `id` column of the `saved_rolls` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Nullable<Integer>,
        /// The `guild_id` column of the `saved_rolls` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> BigInt,
        /// The `user_id` column of the `saved_rolls` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> BigInt,
        /// The `name` column of the `saved_rolls` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `command` column of the `saved_rolls` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        command -> Text,
    }
}

joinable!(saved_roll_aliases -> saved_rolls (saved_roll_id));

allow_tables_to_appear_in_same_query!(
    saved_roll_aliases,
    saved_rolls,
);
